### ISSUE TITLE
Make this as a python 3 compatible.

### ISSUE THREAD

**Issue by imkin** [yandex/django_replicated#20]
I am not sure how much work this may involve but we should make this a python 3 compatible.

Comments?

**Comment by Leden** [comment]
That's a great idea, but here are some concerns.

* AFAIK the core devs of this package use MySQL as a primary RDBMS, and the main python MySQL adapter - [MySQL-python](https://pypi.python.org/pypi/MySQL-python) - still is not Python 3 compatible. So this task won't have a high priority for them in nearest couple of years for sure. They may accept a good pull request implementing Python 3 compability though.

* This library does not seem to have any tests yet, so implementing the support of Python 3 is a rather risky operation in context of introducing some hard-to-spot regressions.

Taking into account the above, some reasonable test coverage should be made first, then the task of making this Python 3 compatible boils down to just making sure that tests pass well on both Python 2 and 3.

**Comment by imkin** [comment]
Agreed @Leden I have a forked repo that has python3 only branch. I am using this with the new mysqlclient driver [https://docs.djangoproject.com/en/1.9/ref/databases/#mysql-db-api-drivers] and it works fine. I am yet to do a lot of end to end testing.

Yes we need a bunch of tests here otherwise any port is risky and by default unstable.

**Comment by eskhool** [comment]
seems to work now...is this bug relevant?

**Comment by imkin** [comment]
@eskhool this was not a bug. I do not have a validation that it works with python3 now.
If you have it. Please feel free to close this.

**Comment by eskhool** [comment]
well, its not crashing with a syntax issue that's all. But it doesn't seem to be sending traffic to my slave server. As I wanted a quick fix solution I just went with django-multidb-router

**Comment by daevaorn** [comment]
`django_replicated` is now fully compatible with python 3.x
