### ISSUE TITLE
Use of 'get_cache' function which is deprecated and removed from Django 1.9

### ISSUE THREAD

**Issue by toracle** [yandex/django_replicated#21]
There is a `get_cache` function which is deprecated and removed from Django 1.9

File "/var/virtualenv/backgrounds/src/django-replicated/django_replicated/db_utils.py", line 8

```
django.core.cache import get_cache, DEFAULT_CACHE_ALIAS
```

**Comment by skoval00** [comment]
I made a pull request for this #22

**Comment by daevaorn** [comment]
Thanks. Fixed with https://github.com/yandex/django_replicated/commit/6a1c19380ecdc1776c3022690457e60cd92752f5
