### ISSUE TITLE
How to use when multi databases are replicated ?

### ISSUE THREAD

**Issue by mced** [yandex/django_replicated#64]
I have several databases living on their own and each are replicated.
How to use this lib with this kind of multi databases setup ?

**Comment by jakiro2017** [comment]
~~I tested this lib and it seems do nothing when slave is down, when master is down, the api is not accessible.~~

please refer this https://github.com/yandex/django_replicated/issues/27#issuecomment-365978643

**Comment by mced** [comment]
@jakiro2017 I will explicit my use case;
I have 2 main databases which store different tables and each of these are replicated.

Something that looks like:
```python
DATABASES = {
    'default': {...},
    'default-slave-1': {...},
    'default-slave-2': {...},

    'timeseries': {...},
    'timeseries-slave-1': {},
    'timeseries-slave-2': {},    
}
```

I guess that using the following will use `timeseries-slave-...` replicas as `default` replica which is not...
```python
REPLICA_DATABASES = [
   'default-slave-1', 'default-slave-2', 'timeseries-slave-1', 'timeseries-slave-2'
]
```

**Comment by jakiro2017** [comment]
My guess is you must write your own router decorator, in my case which use just 1 database (1 master+1 slave) this package works (I must handle myself when master down too)

**Comment by mced** [comment]
Thanks for your reply @jakiro2017 
I close this issue.
